[project]
name = "xpy-teal"
version = "1.0.1"
description = "XPy-Teal: XP Tool for Emission and Absorption Lines"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Sagar Malhotra", email = "malhotrasagar15@gmail.com" },
    { name = "Michael Weiler", email = "mweiler@fqa.ub.edu" }
]
requires-python = ">=3.10"
dependencies = [
    "astroquery>=0.4.11",
    "ipykernel>=7.1.0",
    "joblib>=1.5.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scipy>=1.15.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
